#! /bin/sh

#define startup applications
sxhkd &

~/.config/wpg/wp_init.sh
polybar -r top >>/tmp/pbtop.log 2>&1 &
polybar -r bottom >>/tmp/pbbot.log 2>&1 &
bash ~/scripts/spotify/launchlistener.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

picom --config $HOME/.config/picom/picom.conf &

#Define window settings
bspc config border_width         2
bspc config window_gap           25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding 	 20

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config focus_follows_pointer true
